-- Create tipos_produtos table for managing product types
CREATE TABLE IF NOT EXISTS tipos_produtos (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome text NOT NULL UNIQUE,
  ordem int DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default types
INSERT INTO tipos_produtos (nome, ordem) VALUES
  ('Hambúrguer', 0),
  ('Bebida', 1),
  ('Molho', 2)
ON CONFLICT (nome) DO NOTHING;

-- Enable RLS
ALTER TABLE tipos_produtos ENABLE ROW LEVEL SECURITY;

-- Allow all operations for now (adjust based on your needs)
CREATE POLICY "Allow all access" ON tipos_produtos
  FOR ALL
  USING (true);
